// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Modules.Scheduling.Infrastructure.Database;

#nullable disable

namespace Server.Modules.Scheduling.Infrastructure.Database.Migrations
{
    [DbContext(typeof(SchedulingDbContext))]
    [Migration("20250617091623_DocIdUpadeOnReferral")]
    partial class DocIdUpadeOnReferral
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scheduling")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Modules.Scheduling.Entities.Clinician", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarDescription")
                        .HasColumnType("text");

                    b.Property<string>("AvatarImage")
                        .HasColumnType("text");

                    b.Property<string>("AvatarTitle")
                        .HasColumnType("text");

                    b.Property<int>("ClinicianType")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KeycloakId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LicenceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModifiedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RegulatorType")
                        .HasColumnType("integer");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SubjectKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clinicians", "scheduling");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AvatarDescription = "Senior Doctor, GMC",
                            AvatarImage = "https://randomuser.me/api/portraits/women/1.jpg",
                            AvatarTitle = "Dr. Alice Smith",
                            ClinicianType = 1,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice.smith@example.com",
                            FirstName = "Alice",
                            IsActive = false,
                            KeycloakId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            LastModifiedBy = "System",
                            LastName = "Smith",
                            LicenceNumber = "GMC1001",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegulatorType = 1,
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "555-1001",
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 2L,
                            AvatarDescription = "Junior Doctor, GMC",
                            AvatarImage = "https://randomuser.me/api/portraits/men/2.jpg",
                            AvatarTitle = "Dr. Bob Johnson",
                            ClinicianType = 2,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob.johnson@example.com",
                            FirstName = "Bob",
                            IsActive = false,
                            KeycloakId = new Guid("9c8b7a6d-5e4f-3c2b-1a09-876543210fed"),
                            LastModifiedBy = "System",
                            LastName = "Johnson",
                            LicenceNumber = "GMC1002",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegulatorType = 1,
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "555-1002",
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 3L,
                            AvatarDescription = "Nurse, NMC",
                            AvatarImage = "https://randomuser.me/api/portraits/women/3.jpg",
                            AvatarTitle = "Nurse Carol Williams",
                            ClinicianType = 3,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carol.williams@example.com",
                            FirstName = "Carol",
                            IsActive = false,
                            KeycloakId = new Guid("123e4567-e89b-12d3-a456-426614174000"),
                            LastModifiedBy = "System",
                            LastName = "Williams",
                            LicenceNumber = "NMC1003",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegulatorType = 2,
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "555-1003",
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 4L,
                            AvatarDescription = "Senior Doctor, GMC",
                            AvatarImage = "https://randomuser.me/api/portraits/men/4.jpg",
                            AvatarTitle = "Dr. David Brown",
                            ClinicianType = 1,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.brown@example.com",
                            FirstName = "David",
                            IsActive = false,
                            KeycloakId = new Guid("ba012345-6789-abcd-0123-456789abcdef"),
                            LastModifiedBy = "System",
                            LastName = "Brown",
                            LicenceNumber = "GMC1004",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegulatorType = 1,
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "555-1004",
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 5L,
                            AvatarDescription = "Nurse, NMC",
                            AvatarImage = "https://randomuser.me/api/portraits/women/5.jpg",
                            AvatarTitle = "Nurse Eva Jones",
                            ClinicianType = 3,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eva.jones@example.com",
                            FirstName = "Eva",
                            IsActive = false,
                            KeycloakId = new Guid("00112233-4455-6677-8899-aabbccddeeff"),
                            LastModifiedBy = "System",
                            LastName = "Jones",
                            LicenceNumber = "NMC1005",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegulatorType = 2,
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "555-1005",
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 6L,
                            AvatarDescription = "Junior Doctor, GMC",
                            AvatarImage = "https://randomuser.me/api/portraits/men/6.jpg",
                            AvatarTitle = "Dr. Frank Garcia",
                            ClinicianType = 2,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "frank.garcia@example.com",
                            FirstName = "Frank",
                            IsActive = false,
                            KeycloakId = new Guid("ffeeddcc-bbaa-9988-7766-554433221100"),
                            LastModifiedBy = "System",
                            LastName = "Garcia",
                            LicenceNumber = "GMC1006",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegulatorType = 1,
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "555-1006",
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 7L,
                            AvatarDescription = "Nurse, NMC",
                            AvatarImage = "https://randomuser.me/api/portraits/women/7.jpg",
                            AvatarTitle = "Nurse Grace Martinez",
                            ClinicianType = 3,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "grace.martinez@example.com",
                            FirstName = "Grace",
                            IsActive = false,
                            KeycloakId = new Guid("abcdef01-2345-6789-abcd-ef0123456789"),
                            LastModifiedBy = "System",
                            LastName = "Martinez",
                            LicenceNumber = "NMC1007",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegulatorType = 2,
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "555-1007",
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 8L,
                            AvatarDescription = "Senior Doctor, GMC",
                            AvatarImage = "https://randomuser.me/api/portraits/men/8.jpg",
                            AvatarTitle = "Dr. Henry Lee",
                            ClinicianType = 1,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "henry.lee@example.com",
                            FirstName = "Henry",
                            IsActive = false,
                            KeycloakId = new Guid("fedcba98-7654-3210-fedc-ba9876543210"),
                            LastModifiedBy = "System",
                            LastName = "Lee",
                            LicenceNumber = "GMC1008",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegulatorType = 1,
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "555-1008",
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 9L,
                            AvatarDescription = "Nurse, NMC",
                            AvatarImage = "https://randomuser.me/api/portraits/women/9.jpg",
                            AvatarTitle = "Nurse Ivy Walker",
                            ClinicianType = 3,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivy.walker@example.com",
                            FirstName = "Ivy",
                            IsActive = false,
                            KeycloakId = new Guid("1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"),
                            LastModifiedBy = "System",
                            LastName = "Walker",
                            LicenceNumber = "NMC1009",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegulatorType = 2,
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "555-1009",
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 10L,
                            AvatarDescription = "Junior Doctor, GMC",
                            AvatarImage = "https://randomuser.me/api/portraits/men/10.jpg",
                            AvatarTitle = "Dr. Jack Hall",
                            ClinicianType = 2,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jack.hall@example.com",
                            FirstName = "Jack",
                            IsActive = false,
                            KeycloakId = new Guid("a1b2c3d4-e5f6-a7b8-c9d0-e1f2a3b4c5d6"),
                            LastModifiedBy = "System",
                            LastName = "Hall",
                            LicenceNumber = "GMC1010",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegulatorType = 1,
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "555-1010",
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Server.Modules.Scheduling.Entities.Referral", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmployeeDocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModifiedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferralDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReferralStatus")
                        .HasColumnType("integer");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SubjectKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Referrals", "scheduling");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1L,
                            EmployeeDocumentId = 0L,
                            EmployeeId = 1L,
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReferralDetails = "Routine checkup for hypertension.",
                            ReferralStatus = 0,
                            SubjectId = 1L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 1L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Hypertension Checkup"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1L,
                            EmployeeDocumentId = 0L,
                            EmployeeId = 2L,
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReferralDetails = "Follow-up for diabetes management.",
                            ReferralStatus = 0,
                            SubjectId = 2L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 1L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Diabetes Follow-up"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1L,
                            EmployeeDocumentId = 0L,
                            EmployeeId = 3L,
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReferralDetails = "Initial consultation for back pain.",
                            ReferralStatus = 0,
                            SubjectId = 3L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 1L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Back Pain Consultation"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2L,
                            EmployeeDocumentId = 0L,
                            EmployeeId = 4L,
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReferralDetails = "Annual physical examination.",
                            ReferralStatus = 0,
                            SubjectId = 4L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 2L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Annual Physical Exam"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2L,
                            EmployeeDocumentId = 0L,
                            EmployeeId = 5L,
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReferralDetails = "Referral for allergy testing.",
                            ReferralStatus = 0,
                            SubjectId = 5L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 2L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Allergy Testing"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2L,
                            EmployeeDocumentId = 0L,
                            EmployeeId = 6L,
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReferralDetails = "Consultation for asthma symptoms.",
                            ReferralStatus = 0,
                            SubjectId = 6L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 2L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Asthma Consultation"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3L,
                            EmployeeDocumentId = 0L,
                            EmployeeId = 7L,
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReferralDetails = "Pre-surgery evaluation.",
                            ReferralStatus = 0,
                            SubjectId = 7L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 3L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Pre-Surgery Evaluation"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3L,
                            EmployeeDocumentId = 0L,
                            EmployeeId = 8L,
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReferralDetails = "Post-operative follow-up.",
                            ReferralStatus = 0,
                            SubjectId = 8L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 3L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Post-Op Follow-up"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3L,
                            EmployeeDocumentId = 0L,
                            EmployeeId = 9L,
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReferralDetails = "Referral for physical therapy.",
                            ReferralStatus = 0,
                            SubjectId = 9L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 3L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Physical Therapy Referral"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3L,
                            EmployeeDocumentId = 0L,
                            EmployeeId = 10L,
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReferralDetails = "Consultation for migraine headaches.",
                            ReferralStatus = 0,
                            SubjectId = 10L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 3L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Migraine Consultation"
                        });
                });

            modelBuilder.Entity("Server.Modules.Scheduling.Entities.Schedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("integer");

                    b.Property<long>("ClinicianId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModifiedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReferralId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SubjectKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClinicianId");

                    b.HasIndex("ReferralId");

                    b.ToTable("Schedules", "scheduling");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AppointmentStatus = 0,
                            ClinicianId = 1L,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1L,
                            Description = "Regular blood pressure monitoring and medication review",
                            EmployeeId = 1L,
                            End = new DateTime(2025, 4, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 0L,
                            ReferralId = 1L,
                            Start = new DateTime(2025, 4, 22, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            SubjectId = 1L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 1L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Blood Pressure Check-up"
                        },
                        new
                        {
                            Id = 2L,
                            AppointmentStatus = 0,
                            ClinicianId = 2L,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1L,
                            Description = "Review of blood sugar levels and medication adjustment",
                            EmployeeId = 2L,
                            End = new DateTime(2025, 4, 22, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 0L,
                            ReferralId = 2L,
                            Start = new DateTime(2025, 4, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            SubjectId = 2L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 1L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Diabetes Follow-up"
                        },
                        new
                        {
                            Id = 3L,
                            AppointmentStatus = 0,
                            ClinicianId = 3L,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1L,
                            Description = "Initial evaluation of chronic lower back pain",
                            EmployeeId = 3L,
                            End = new DateTime(2025, 4, 22, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 0L,
                            ReferralId = 3L,
                            Start = new DateTime(2025, 4, 22, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            SubjectId = 3L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 1L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Back Pain Assessment"
                        });
                });

            modelBuilder.Entity("Server.Modules.Scheduling.Entities.Schedule", b =>
                {
                    b.HasOne("Server.Modules.Scheduling.Entities.Clinician", null)
                        .WithMany("CalendarItems")
                        .HasForeignKey("ClinicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Modules.Scheduling.Entities.Referral", null)
                        .WithMany("CalendarItems")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Modules.Scheduling.Entities.Clinician", b =>
                {
                    b.Navigation("CalendarItems");
                });

            modelBuilder.Entity("Server.Modules.Scheduling.Entities.Referral", b =>
                {
                    b.Navigation("CalendarItems");
                });
#pragma warning restore 612, 618
        }
    }
}
