// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Modules.CRM.Infrastructure.Database;

#nullable disable

namespace Server.Modules.CRM.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CRMDbContext))]
    [Migration("20250620161702_AddSearchTagsToAllRelevantEntities")]
    partial class AddSearchTagsToAllRelevantEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("crm")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Modules.CRM.Entities.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModifiedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RepresentativeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SubjectKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantKeycloakId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Contracts", "crm");
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvoiceEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KeycloakId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModifiedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfEmployees")
                        .HasColumnType("integer");

                    b.Property<string>("OHServicesRequired")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchTags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SubjectKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers", "crm");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "1 Acme Street, London",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 0L,
                            Email = "info@acme.example.com",
                            Industry = "Technology",
                            InvoiceEmail = "accounts@acme.example.com",
                            IsActive = true,
                            KeycloakId = new Guid("11111111-1111-1111-1111-111111111111"),
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Acme Corp",
                            Notes = "Key client.",
                            NumberOfEmployees = 100,
                            OHServicesRequired = "Full OH Service",
                            Postcode = "AC1 2ME",
                            SearchTags = "1 Acme Corp 1 Acme Street London AC1 2ME 01234 567890",
                            Site = "London",
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "01234 567890",
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Website = "https://acme.example.com"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "2 Beta Road, Manchester",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 0L,
                            Email = "contact@beta.example.com",
                            Industry = "Manufacturing",
                            InvoiceEmail = "finance@beta.example.com",
                            IsActive = true,
                            KeycloakId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Beta Ltd",
                            Notes = "Annual contract.",
                            NumberOfEmployees = 50,
                            OHServicesRequired = "Health Surveillance",
                            Postcode = "BT2 3LT",
                            SearchTags = "2 Beta Ltd 2 Beta Road Manchester BT2 3LT 02345 678901",
                            Site = "Manchester",
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "02345 678901",
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Website = "https://beta.example.com"
                        },
                        new
                        {
                            Id = 3L,
                            Address = "3 Gamma Avenue, Birmingham",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 0L,
                            Email = "hello@gamma.example.com",
                            Industry = "Logistics",
                            InvoiceEmail = "billing@gamma.example.com",
                            IsActive = true,
                            KeycloakId = new Guid("33333333-3333-3333-3333-333333333333"),
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gamma Inc",
                            Notes = "Occasional work.",
                            NumberOfEmployees = 200,
                            OHServicesRequired = "Ad hoc assessments",
                            Postcode = "GM3 4IN",
                            SearchTags = "",
                            Site = "Birmingham",
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "03456 789012",
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Website = "https://gamma.example.com"
                        },
                        new
                        {
                            Id = 20L,
                            Address = "First Floor, Swan Buildings, 20 Swan Street, Manchester",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 0L,
                            Email = "contact@nationoh.co.uk",
                            Industry = "Occupatioanl Health",
                            InvoiceEmail = "contact@nationoh.co.uk",
                            IsActive = true,
                            KeycloakId = new Guid("44444444-4444-4444-4444-444444444444"),
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Nation Occupational Health",
                            Notes = "",
                            NumberOfEmployees = 200,
                            OHServicesRequired = "Ad hoc assessments",
                            Postcode = "M4 5JW",
                            SearchTags = "20 Nation Occupational Health First Floor Swan Buildings 20 Swan Street Manchester M4 5JW 01147 004 362",
                            Site = "Birmingham",
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "01147 004 362",
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Website = "https://www.nationoh.co.uk"
                        });
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.CustomerDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BlobContainerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModifiedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchTags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SubjectKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantKeycloakId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerDocuments", "crm");
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .HasColumnType("text");

                    b.Property<string>("Address3")
                        .HasColumnType("text");

                    b.Property<string>("AvatarDescription")
                        .HasColumnType("text");

                    b.Property<string>("AvatarImage")
                        .HasColumnType("text");

                    b.Property<string>("AvatarTitle")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JobRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("KeycloakId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LineManager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ManagerId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ModifiedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchTags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SubjectKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees", "crm");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address1 = "1 Main St",
                            Address2 = "Apt 1",
                            Address3 = "",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1L,
                            DOB = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Email = "alice.smith@example.com",
                            FirstName = "Alice",
                            IsActive = true,
                            JobRole = "Manager",
                            KeycloakId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            LastModifiedBy = "System",
                            LastName = "Smith",
                            LineManager = "Bob Jones",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "",
                            Postcode = "EMP1 1AA",
                            SearchTags = "1 Alice Smith 1 Main St Apt 1 EMP1 1AA 07111 111111",
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "07111 111111",
                            TenantId = 1L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 2L,
                            Address1 = "2 Main St",
                            Address2 = "Apt 2",
                            Address3 = "",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2L,
                            DOB = new DateTime(1985, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "IT",
                            Email = "bob.jones@example.com",
                            FirstName = "Bob",
                            IsActive = true,
                            JobRole = "Engineer",
                            KeycloakId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            LastModifiedBy = "System",
                            LastName = "Jones",
                            LineManager = "Carol White",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "",
                            Postcode = "EMP2 2BB",
                            SearchTags = "2 Bob Jones 2 Main St Apt 2 EMP2 2BB 07222 222222",
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "07222 222222",
                            TenantId = 2L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 3L,
                            Address1 = "3 Main St",
                            Address2 = "Apt 3",
                            Address3 = "",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3L,
                            DOB = new DateTime(1992, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Email = "carol.white@example.com",
                            FirstName = "Carol",
                            IsActive = true,
                            JobRole = "Analyst",
                            KeycloakId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            LastModifiedBy = "System",
                            LastName = "White",
                            LineManager = "David Black",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "",
                            Postcode = "EMP3 3CC",
                            SearchTags = "3 Carol White 3 Main St Apt 3 EMP3 3CC 07333 333333",
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "07333 333333",
                            TenantId = 3L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 4L,
                            Address1 = "4 Main St",
                            Address2 = "Apt 4",
                            Address3 = "",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1L,
                            DOB = new DateTime(1988, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Consulting",
                            Email = "david.black@example.com",
                            FirstName = "David",
                            IsActive = true,
                            JobRole = "Consultant",
                            KeycloakId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            LastModifiedBy = "System",
                            LastName = "Black",
                            LineManager = "Alice Smith",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "",
                            Postcode = "EMP4 4DD",
                            SearchTags = "4 David Black 4 Main St Apt 4 EMP4 4DD 07444 444444",
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "07444 444444",
                            TenantId = 1L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 5L,
                            Address1 = "5 Main St",
                            Address2 = "Apt 5",
                            Address3 = "",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2L,
                            DOB = new DateTime(1995, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Medical",
                            Email = "eve.green@example.com",
                            FirstName = "Eve",
                            IsActive = true,
                            JobRole = "Nurse",
                            KeycloakId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            LastModifiedBy = "System",
                            LastName = "Green",
                            LineManager = "Bob Jones",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "",
                            Postcode = "EMP5 5EE",
                            SearchTags = "5 Eve Green 5 Main St Apt 5 EMP5 5EE 07555 555555",
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "07555 555555",
                            TenantId = 2L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 6L,
                            Address1 = "6 Main St",
                            Address2 = "Apt 6",
                            Address3 = "",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3L,
                            DOB = new DateTime(1983, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Support",
                            Email = "frank.blue@example.com",
                            FirstName = "Frank",
                            IsActive = true,
                            JobRole = "Technician",
                            KeycloakId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            LastModifiedBy = "System",
                            LastName = "Blue",
                            LineManager = "Carol White",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "",
                            Postcode = "EMP6 6FF",
                            SearchTags = "6 Frank Blue 6 Main St Apt 6 EMP6 6FF 07666 666666",
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "07666 666666",
                            TenantId = 3L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 7L,
                            Address1 = "7 Main St",
                            Address2 = "Apt 7",
                            Address3 = "",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1L,
                            DOB = new DateTime(1991, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Advisory",
                            Email = "grace.brown@example.com",
                            FirstName = "Grace",
                            IsActive = true,
                            JobRole = "Advisor",
                            KeycloakId = new Guid("11111111-aaaa-aaaa-aaaa-111111111111"),
                            LastModifiedBy = "System",
                            LastName = "Brown",
                            LineManager = "David Black",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "",
                            Postcode = "EMP7 7GG",
                            SearchTags = "7 Grace Brown 7 Main St Apt 7 EMP7 7GG 07777 777777",
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "07777 777777",
                            TenantId = 1L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 8L,
                            Address1 = "8 Main St",
                            Address2 = "Apt 8",
                            Address3 = "",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2L,
                            DOB = new DateTime(1987, 8, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Logistics",
                            Email = "henry.gray@example.com",
                            FirstName = "Henry",
                            IsActive = true,
                            JobRole = "Driver",
                            KeycloakId = new Guid("22222222-bbbb-bbbb-bbbb-222222222222"),
                            LastModifiedBy = "System",
                            LastName = "Gray",
                            LineManager = "Eve Green",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "",
                            Postcode = "EMP8 8HH",
                            SearchTags = "8 Henry Gray 8 Main St Apt 8 EMP8 8HH 07888 888888",
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "07888 888888",
                            TenantId = 2L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 9L,
                            Address1 = "9 Main St",
                            Address2 = "Apt 9",
                            Address3 = "",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3L,
                            DOB = new DateTime(1993, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Admin",
                            Email = "ivy.violet@example.com",
                            FirstName = "Ivy",
                            IsActive = true,
                            JobRole = "Receptionist",
                            KeycloakId = new Guid("33333333-cccc-cccc-cccc-333333333333"),
                            LastModifiedBy = "System",
                            LastName = "Violet",
                            LineManager = "Frank Blue",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "",
                            Postcode = "EMP9 9II",
                            SearchTags = "9 Ivy Violet 9 Main St Apt 9 EMP9 9II 07999 999999",
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "07999 999999",
                            TenantId = 3L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 10L,
                            Address1 = "10 Main St",
                            Address2 = "Apt 10",
                            Address3 = "",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1L,
                            DOB = new DateTime(1989, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Facilities",
                            Email = "jack.white@example.com",
                            FirstName = "Jack",
                            IsActive = true,
                            JobRole = "Cleaner",
                            KeycloakId = new Guid("44444444-dddd-dddd-dddd-444444444444"),
                            LastModifiedBy = "System",
                            LastName = "White",
                            LineManager = "Grace Brown",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "",
                            Postcode = "EMP10 0JJ",
                            SearchTags = "10 Jack White 10 Main St Apt 10 EMP10 0JJ 07000 000000",
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "07000 000000",
                            TenantId = 1L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.EmployeeDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BlobContainerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModifiedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchTags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SubjectKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantKeycloakId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeDocuments", "crm");
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Manager", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarDescription")
                        .HasColumnType("text");

                    b.Property<string>("AvatarImage")
                        .HasColumnType("text");

                    b.Property<string>("AvatarTitle")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KeycloakId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModifiedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SearchTags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SubjectKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Managers", "crm");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1L,
                            Department = "HR",
                            Email = "thompson.smith@example.com",
                            FirstName = "Thompson",
                            IsActive = false,
                            KeycloakId = new Guid("55555555-5555-5555-5555-555555555555"),
                            LastModifiedBy = "System",
                            LastName = "Smith",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SearchTags = "1 Thompson Smith 1 Acme Street London AC1 2ME 07111 111111",
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "07111 111111",
                            TenantId = 1L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2L,
                            Department = "Finance",
                            Email = "emily.johnson@example.com",
                            FirstName = "Emily",
                            IsActive = false,
                            KeycloakId = new Guid("66666666-6666-6666-6666-666666666666"),
                            LastModifiedBy = "System",
                            LastName = "Johnson",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SearchTags = "2 Emily Johnson 2 Beta Road Manchester BT2 3LT 07222 222222",
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "07222 222222",
                            TenantId = 2L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3L,
                            Department = "IT",
                            Email = "michael.brown@example.com",
                            FirstName = "Michael",
                            IsActive = false,
                            KeycloakId = new Guid("77777777-7777-7777-7777-777777777777"),
                            LastModifiedBy = "System",
                            LastName = "Brown",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SearchTags = "3 Michael Brown 3 Gamma Avenue Birmingham GM3 4IN 07333 333333",
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Telephone = "07333 333333",
                            TenantId = 3L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModifiedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<long>("ProductTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SubjectKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantKeycloakId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products", "crm");
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.ProductType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChargeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModifiedByKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SubjectKeycloakId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantKeycloakId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes", "crm");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ChargeCode = "OHPFULL",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "OHP Full Day",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OHP Full Day",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 2L,
                            ChargeCode = "OHPHALF",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 1000m,
                            Description = "OHP Half Day",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OHP Half Day",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 3L,
                            ChargeCode = "OHAFULL",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "OHA Full Day",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OHA Full Day",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 4L,
                            ChargeCode = "OHAHALF",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "OHA Half Day",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OHA Half Day",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 5L,
                            ChargeCode = "OHTFULLDAY",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "OHT Full Day",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OHT Full Day",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 6L,
                            ChargeCode = "OHPAPP",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "OHP Appointment",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OHP Appointment",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 7L,
                            ChargeCode = "OHPPENS",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Pensions Case",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pensions Case",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 8L,
                            ChargeCode = "OHPAUDIO",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Audiometry Reviews (per 15 mins)",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Audiometry Reviews (per 15 mins)",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 9L,
                            ChargeCode = "RETAIN",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Monthly Retainer Fee",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Monthly Retainer Fee",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 10L,
                            ChargeCode = "OHPTIME",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "OHP Consultancy Time (per 15 mins)",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OHP Consultancy Time (per 15 mins)",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 11L,
                            ChargeCode = "PPHA",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Pre Placement Health Assessment",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pre Placement Health Assessment",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 12L,
                            ChargeCode = "PPHA15",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Pre Placement Health Assessment (per 15 mins)",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pre Placement Health Assessment (per 15 mins)",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 13L,
                            ChargeCode = "MTRC",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Mileage and Travel Re-Charged to Customer (per mile)",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mileage and Travel Re-Charged to Customer (per mile)",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 14L,
                            ChargeCode = "ARC",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Accommodation Recharged to Customer",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Accommodation Recharged to Customer",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 15L,
                            ChargeCode = "CRC",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Consumables Recharged to Customer",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consumables Recharged to Customer",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 16L,
                            ChargeCode = "PSRC",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Physiotherapy Services Recharged to Customer",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Physiotherapy Services Recharged to Customer",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 17L,
                            ChargeCode = "GPSR",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "GP / Specialist Report Recharged",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GP / Specialist Report Recharged",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 18L,
                            ChargeCode = "ADMIN",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Administration Time",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Administration Time",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 19L,
                            ChargeCode = "HAVS1",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "HAVS Tier 1",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HAVS Tier 1",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 20L,
                            ChargeCode = "HAVS2",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "HAVS Tier 2",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HAVS Tier 2",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 21L,
                            ChargeCode = "HAVS3",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "HAVS Tier 3",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HAVS Tier 3",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 22L,
                            ChargeCode = "HAVS4",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "HAVS Tier 4",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HAVS Tier 4",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 23L,
                            ChargeCode = "OHPFULLCOMPLEX",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "OHP Full Complex",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OHP Full Complex",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 24L,
                            ChargeCode = "PTSMINI",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "PTS / Rail Work mini audit",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PTS / Rail Work mini audit",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 25L,
                            ChargeCode = "PTSPAPER",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "PTS / Rail Work paper based review",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PTS / Rail Work paper based review",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 26L,
                            ChargeCode = "PTSAUDIT",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "PTS / Rail Work audit of cases",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PTS / Rail Work audit of cases",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 27L,
                            ChargeCode = "PTSRETAIN",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "PTS / Rail Work Retainer (per month)",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PTS / Rail Work Retainer (per month)",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 28L,
                            ChargeCode = "PTSADD",
                            CreatedBy = "System",
                            CreatedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Additional PTS or MRO work or reporting (per 15 mins)",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = "System",
                            ModifiedByKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Additional PTS or MRO work or reporting (per 15 mins)",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 0L,
                            SubjectKeycloakId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = 0L,
                            TenantKeycloakId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Contract", b =>
                {
                    b.HasOne("Server.Modules.CRM.Entities.Customer", null)
                        .WithMany("Contracts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.CustomerDocument", b =>
                {
                    b.HasOne("Server.Modules.CRM.Entities.Customer", null)
                        .WithMany("Documents")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Employee", b =>
                {
                    b.HasOne("Server.Modules.CRM.Entities.Customer", null)
                        .WithMany("Employees")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Modules.CRM.Entities.Manager", null)
                        .WithMany("Employees")
                        .HasForeignKey("ManagerId");
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.EmployeeDocument", b =>
                {
                    b.HasOne("Server.Modules.CRM.Entities.Employee", null)
                        .WithMany("Documents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Manager", b =>
                {
                    b.HasOne("Server.Modules.CRM.Entities.Customer", null)
                        .WithMany("Managers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Product", b =>
                {
                    b.HasOne("Server.Modules.CRM.Entities.Customer", null)
                        .WithMany("Products")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Modules.CRM.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Customer", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Documents");

                    b.Navigation("Employees");

                    b.Navigation("Managers");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Employee", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Manager", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
