name: Terraform Infrastructure

on:
  push: 
<<<<<<< HEAD
    branches: [master, production, devops-setup]
    paths:
      - "NationOH/infra/**"
      - ".github/workflows/terraform.yml"
  pull_request:
    branches: [master]
    paths:
      - "NationOH/infra/**"
=======
    branches: [master, production]
    paths:
      -"NationOH/infra/**"
      -".github/workflows/terraform.yml"
  pull_request:
    branches: [master]
    paths:
      -"NationOH/infra/**"
>>>>>>> origin/devops-setup
      

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Environment Variables 
      id: vars
      run: |
        if [[ ${{ github.ref }} == "refs/heads/production" ]]; then
           echo "ENV_NAME=prod" >> $GITHUB_OUTPUT
           echo "TF_VAR_FILE=prod.tfvars" >> $GITHUB_OUTPUT
           echo "TF_STATE_KEY=nationoh/prod.tfstate" >> $GITHUB_OUTPUT
        elif [[ ${{ github.ref }} == "refs/heads/master" ]]; then
          echo "ENV_NAME=dev" >> $GITHUB_OUTPUT
          echo "TF_VAR_FILE=dev.tfvars" >> $GITHUB_OUTPUT
          echo "TF_STATE_KEY=nationoh/dev.tfstate" >> $GITHUB_OUTPUT
        elif [[ ${{ github.ref }} == "refs/heads/devops-setup" ]]; then
          echo "ENV_NAME=dev" >> $GITHUB_OUTPUT
          echo "TF_VAR_FILE=dev.tfvars" >> $GITHUB_OUTPUT
          echo "TF_STATE_KEY=nationoh/dev.tfstate" >> $GITHUB_OUTPUT
        fi

    - name: Terraform Init
      working-directory: ./NationOH/infra
      run: |
        terraform init \
          -backend-config="key=${{ steps.vars.outputs.TF_STATE_KEY }}"
    
    - name: Terraform Format
      working-directory: ./NationOH/infra
      run: terraform fmt -check

    - name: Terraform Plan
      working-directory: ./NationOH/infra
      run: terraform plan -var-file="${{ steps.vars.outputs.TF_VAR_FILE }}" -out=tfplan

    - name: Terraform Apply
      working-directory: ./NationOH/infra
      run: terraform apply -auto-approve tfplan