name: Terraform Infrastructure

on:
  push: 
    branches: [master, production, devops-setup]
    paths:
      - "infra/**"
      - ".github/workflows/terraform.yml"
  pull_request:
    branches: [master]
    paths:
      - "infra/**"
      

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

# will need to remove the devops-setup branch and the uk_south flag when we move to production and merge with master 
    - name: Set Environment Variables 
      id: vars
      run: |
        if [[ ${{ github.ref }} == "refs/heads/production" ]]; then
           echo "ENV_NAME=prod" >> $GITHUB_OUTPUT
           echo "TF_VAR_FILE=prod.tfvars" >> $GITHUB_OUTPUT
           echo "TF_STATE_KEY=nationoh/prod.tfstate" >> $GITHUB_OUTPUT
        elif [[ ${{ github.ref }} == "refs/heads/master" ]]; then
          echo "ENV_NAME=dev" >> $GITHUB_OUTPUT
          echo "TF_VAR_FILE=dev.tfvars" >> $GITHUB_OUTPUT
          echo "TF_STATE_KEY=nationoh/dev.tfstate" >> $GITHUB_OUTPUT
        elif [[ ${{ github.ref }} == "refs/heads/devops-setup" ]]; then
          echo "ENV_NAME=dev" >> $GITHUB_OUTPUT
          echo "TF_VAR_FILE=dev.tfvars" >> $GITHUB_OUTPUT
          echo "TF_STATE_KEY=nationoh/dev.tfstate" >> $GITHUB_OUTPUT
        fi

    - name: Clear Terraform Cache
      working-directory: ./infra
      run: |
        rm -rf .terraform
        rm -f .terraform.lock.hcl
        rm -f terraform.tfstate*

    - name: Terraform Init
      working-directory: ./infra
      run: |
        terraform init \
          -backend-config="key=${{ steps.vars.outputs.TF_STATE_KEY }}"
    # Add these steps after the terraform init step and before the terraform plan step
    - name: Import existing resources
      run: |
        cd infra
        # Import primary resources
        terraform import module.networking.azurerm_virtual_network.vnet /subscriptions/ba3bebaa-e2fc-47da-b577-2830ffd32473/resourceGroups/nationohdev/providers/Microsoft.Network/virtualNetworks/nationoh-vnet || true
        terraform import module.networking.azurerm_network_security_group.nsg["appgateway"] /subscriptions/ba3bebaa-e2fc-47da-b577-2830ffd32473/resourceGroups/nationohdev/providers/Microsoft.Network/networkSecurityGroups/appgateway-nsg || true
        terraform import module.networking.azurerm_network_security_group.nsg["data"] /subscriptions/ba3bebaa-e2fc-47da-b577-2830ffd32473/resourceGroups/nationohdev/providers/Microsoft.Network/networkSecurityGroups/data-nsg || true
        terraform import module.networking.azurerm_network_security_group.nsg["privatelink"] /subscriptions/ba3bebaa-e2fc-47da-b577-2830ffd32473/resourceGroups/nationohdev/providers/Microsoft.Network/networkSecurityGroups/privatelink-nsg || true
        terraform import module.monitoring.azurerm_log_analytics_workspace.log_analytics /subscriptions/ba3bebaa-e2fc-47da-b577-2830ffd32473/resourceGroups/nationohdev/providers/Microsoft.OperationalInsights/workspaces/nationohdev-insights-workspace-tf || true
        terraform import module.application_gateway.azurerm_public_ip.app_gateway_ip /subscriptions/ba3bebaa-e2fc-47da-b577-2830ffd32473/resourceGroups/nationohdev/providers/Microsoft.Network/publicIPAddresses/nationohdev-app-gateway-ip || true
        terraform import module.application_gateway.azurerm_web_application_firewall_policy.waf_policy /subscriptions/ba3bebaa-e2fc-47da-b577-2830ffd32473/resourceGroups/nationohdev/providers/Microsoft.Network/applicationGatewayWebApplicationFirewallPolicies/nationohdev-waf-policy || true
        terraform import module.registry.azurerm_container_registry.acr /subscriptions/ba3bebaa-e2fc-47da-b577-2830ffd32473/resourceGroups/nationohdev/providers/Microsoft.ContainerRegistry/registries/nationohdevregistry || true
        terraform import module.registry.azurerm_user_assigned_identity.acr_identity /subscriptions/ba3bebaa-e2fc-47da-b577-2830ffd32473/resourceGroups/nationohdev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/nationohdevregistry-identity || true
    
    # temporary fix for the issue of refreshing the state file to deploy in a different location 
    - name: Terraform Refresh
      working-directory: ./infra
      run: terraform refresh -var-file="${{ steps.vars.outputs.TF_VAR_FILE }}"
    
    - name: Terraform Format
      working-directory: ./infra
      run: terraform fmt -check

    - name: Terraform Plan
      working-directory: ./infra
      run: terraform plan -var-file="${{ steps.vars.outputs.TF_VAR_FILE }}" -out=tfplan

    - name: Terraform Apply
      working-directory: ./infra
      run: terraform apply -auto-approve tfplan